### ISSUE TITLE
Update commander to the latest version

### ISSUE THREAD

**Issue by XhmikosR** [XhmikosR/find-unused-sass-variables#100]
And make use of variadic options

**Comment by danny007in** [comment]
what is variadic options
so i can solve

**Comment by XhmikosR** [comment]
https://github.com/tj/commander.js/pull/1250

Also, this is a major version bump, I'm not sure if there any other breaking changes after 5.1.0 that affect us.

**Comment by danny007in** [comment]
in cleancss-cli they have migrated commander to v2 to v7.
so we do by checking there diff

**Comment by XhmikosR** [comment]
Each project is unique, so it's not the same procedure. And here, we don't really have CLI tests apart from a basic one.

**Comment by XhmikosR** [comment]
Fixed by #138
