### ISSUE TITLE
Fails on files with UTF-8 with signature / 0xFEFF / BOM

### ISSUE THREAD

**Issue by AndersMad** [XhmikosR/find-unused-sass-variables#168]
**Problem:** Parser will yield errors like `CssSyntaxError: <css input>:x:x: Unknown word`

**Quick fix:** In file index.js change `sassStr += fs.readFileSync(file, 'utf8');` to e.g.
```js
let data = fs.readFileSync(file, 'utf-8');

// Remove 0xFEFF / BOM / UTF-8 with signature
if (data.startsWith("ï»¿")) {
    data = data.substring(1);
}

sassStr += data;
```

**Comment by XhmikosR** [comment]
Why would you use BOM? We could probably work around the issue here but I honestly don't see any reason for anyone to use BOM. You can enforce this with Stylelint https://stylelint.io/user-guide/rules/list/unicode-bom/

**Comment by AndersMad** [comment]
I would not - but someone did, and someone will (not all systems be static developer stack - SCSS is here runtime compiled). And since it concats all the files in to one chunk - it was a pretty hard find /õ\ (each single source with BOM will parse ok).

At least if someone else bumps into this - they maybe will find this one.

**Comment by XhmikosR** [comment]
https://github.com/sindresorhus/strip-bom/blob/main/index.js
