### ISSUE TITLE
Add ignore file(s) support

### ISSUE THREAD

**Issue by AndersMad** [XhmikosR/find-unused-sass-variables#169]
Let's you ignore SCSS file(s):

Change in index.js
```js
const sassFiles = glob.sync(path.join(dir, '**/*.scss'), { ignore: opt.ignoreFiles });
```

Usage: 
```js
const unused = fusv.find("./scss", { ignoreFiles: ["**/_crappy-vars.scss"], ignore: ["$crappy-var"] });`
```

**Comment by Dervisevic** [comment]
+1 would love to have this feature as well. We have a style-dictionary generated file that has a lot of unused variables and would be great to be able to ignore it and not have it sit elsewhere to avoid getting scanned.

**Comment by XhmikosR** [comment]
Happy to accept a clean PR with tests :)
