### ISSUE TITLE
Stylelint plugin

### ISSUE THREAD

**Issue by MartijnCuppens** [XhmikosR/find-unused-sass-variables#25]
It would be nice if this could be a stylelint plugin, maybe we can just extend https://github.com/kristerkari/stylelint-scss?

**Comment by Johann-S** [comment]
Nice idea ! 
What do you think @XhmikosR ?

**Comment by XhmikosR** [comment]
Definitely in favor of this :)

Should have thought of this earlier, but this evolved from a bash script to
a nice script and then this.

**Comment by XhmikosR** [comment]
Which reminds me, I should go through stylelint-scss options and see if we can enable more for Bootstrap. Oh, @MartijnCuppens BTW I closed this but maybe you are interested in it https://github.com/twbs/bootstrap/issues/24519

**Comment by MartijnCuppens** [comment]
Anyone here who wants to look into this?

**Comment by XhmikosR** [comment]
Sorry for the late reply, please go ahead with this if you have time and CC us :)

**Comment by XhmikosR** [comment]
It seems there's a Stylelint plugin here https://github.com/primer/stylelint-config/tree/main/plugins#primerno-unused-vars
