### ISSUE TITLE
Exit code (v0.4.0)

### ISSUE THREAD

**Issue by ashfahan** [XhmikosR/find-unused-sass-variables#31]
Shouldn't the script generate error when some unused variable is found ?

Spec :
Using Npm version

Expected behavior (0.3.3):
![0 3 3](https://user-images.githubusercontent.com/19289015/61161755-bd987d00-a51e-11e9-8bc4-bb148ddc7271.png)

v0.4.0 behavior:
![4 0](https://user-images.githubusercontent.com/19289015/61161762-c25d3100-a51e-11e9-8c66-7fd7b79f15e1.png)

**Comment by XhmikosR** [comment]
Hmm, must have broken in the latest patch.

/CC @Johann-S: can you have a look please? Maybe we should check the exit code in tests to prevent this from happening again?

**Comment by ashfahan** [comment]
Maybe add `process.exit(1);` in else statement?

https://github.com/XhmikosR/find-unused-sass-variables/blob/33c24a11647fe41717553ec83fde736b08fd2503/cli.js#L50-L53

**Comment by XhmikosR** [comment]
Probably the exit code should be the number of unused variables found.

**Comment by ashfahan** [comment]
something like ? 😄 

<pre>
} else {
      spinner.fail(`${unusedList.length} unsed variables found !`);
}</pre>

**Comment by Johann-S** [comment]
I agree with @ashfahan we should use process.exit and yes I think it's due to the move to commander
