### ISSUE TITLE
Switch to async functions

### ISSUE THREAD

**Issue by XhmikosR** [XhmikosR/find-unused-sass-variables#8]
Except for `fs.existsSync` which isn't deprecated, but including `glob`.

EDIT:
We might need to switch to `globby` too.

Also, we should probably keep a `fusv.sync` method.

EDIT2: we can keep glob and use `util.promisify` probably.

**Comment by Johann-S** [comment]
Sorry to ask but what's the reason to switch to async functions ?

**Comment by XhmikosR** [comment]
https://nodejs.org/en/docs/guides/blocking-vs-non-blocking/

**Comment by Johann-S** [comment]
Maybe pify can help us ? https://github.com/sindresorhus/pify
